#!/bin/sh
# Toglie il marchio «scaricato da internet» dall'app appena installata, così non compare un secondo avviso all'apertura.
for app in /Applications/Fluidigram.app "$HOME/Applications/Fluidigram.app" "$2/Fluidigram.app"; do
  [ -d "$app" ] && xattr -cr "$app" 2>/dev/null
done
exit 0
